export const adminHTML = `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>专属链接 · Mingrui Liang</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#162333;font:16px/1.6 system-ui,sans-serif}main{max-width:1080px;margin:48px auto;padding:0 24px}h1{font-size:32px;letter-spacing:-1px;margin:8px 0}h2{font-size:20px}small,.muted{color:#64748b}.card{background:white;border:1px solid #dce3ed;border-radius:16px;padding:24px;margin:20px 0}label{display:block;font-weight:600;margin:12px 0 5px}input,select,button{font:inherit;border:1px solid #cad3e0;border-radius:8px;padding:10px 14px}input,select{width:100%;background:white;color:#162333}button{cursor:pointer;background:#245c86;color:white}button.secondary{background:white;color:#245c86}button:disabled{opacity:.5}.row{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.row>label{flex:1;min-width:200px}.bar{display:flex;justify-content:space-between;align-items:center;gap:12px}.error{color:#9f2525}#message{min-height:24px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #e4eaf2;padding:14px 10px;vertical-align:top}td button{font-size:13px;padding:5px 9px;margin:3px}th{color:#64748b;font-size:13px}td small{display:block}a{color:#245c86}.tablewrap{overflow:auto}[hidden]{display:none!important}.count{font-size:24px;font-weight:700}.badge{background:#e8f1f8;padding:2px 8px;border-radius:20px;font-size:12px}#output{font-family:monospace;font-size:13px}dialog{border:1px solid #cad3e0;border-radius:16px;max-width:700px;width:90%;max-height:80vh}dialog::backdrop{background:#13253a88}.note{font-size:14px}#login{max-width:520px}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #9ec5e5;outline-offset:2px}@media(max-width:600px){main{margin:24px auto;padding:0 16px}.card{padding:16px}.bar{align-items:start}h1{font-size:27px}}
</style></head><body><main><small>PRIVATE DASHBOARD / MINGRUI LIANG</small><div class="bar"><h1>专属链接访问统计</h1><button id="logout" class="secondary" hidden>退出登录</button></div><p class="muted">识别哪个专属链接被打开；不代表已确认访问者本人。</p><p id="message" role="status" aria-live="polite"></p>
<form id="login" class="card"><h2>管理员登录</h2><label for="password">登录密钥</label><input id="password" type="password" autocomplete="current-password" required><p><button>登录</button></p><small>仅管理员可查看备注和访问记录。密钥不会写入公开网站。</small></form>
<section id="dashboard" hidden><form id="create" class="card"><h2>创建分享链接</h2><div class="row"><label>收件人备注<input id="label" maxlength="100" placeholder="例如：A 教授 / 招聘联系人" required></label><label>打开页面<select id="path"><option value="/">个人主页</option><option value="/cv/">Full CV</option><option value="/publications/">Publications</option><option value="/demos/singing-voice-conversion/">Singing voice conversion demo</option></select></label><button>生成链接</button></div><div id="generated" hidden><label for="output">复制这个链接发送给对应的人</label><div class="row"><input id="output" readonly><button id="copy-new" type="button" class="secondary">复制链接</button></div></div></form>
<div class="card"><div class="bar"><div><h2>链接列表 <span id="total" class="badge"></span></h2><small>访问次数为最近 90 天的页面访问事件，按浏览器本地时间显示。</small></div><button id="refresh" class="secondary">刷新</button></div><div class="tablewrap"><table><thead><tr><th>备注 / 页面</th><th>访问次数</th><th>最近访问</th><th>操作</th></tr></thead><tbody id="rows"></tbody></table></div><p id="empty" hidden>还没有专属链接。先在上方输入备注生成一个。</p></div>
<p class="muted note">仅页面可见并停留约 5 秒后记录；同一会话、同一页面每 30 分钟时段至多记一次。停用后不再记录，链接仍可打开网站。记录保留 90 天。链接转发、机器人和隐私设置会影响统计，次数不等于独立人数。</p></section>
<dialog id="details"><div class="bar"><h2 id="detail-title">访问记录</h2><button id="close" class="secondary">关闭</button></div><p class="muted">最近 200 条记录</p><div id="detail-list"></div></dialog></main>
<script>
const $=id=>document.getElementById(id);let site='';
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':'';}
async function api(path,method='GET',data){const res=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});const result=await res.json();if(!res.ok){if(res.status===401){$('dashboard').hidden=true;$('login').hidden=false;$('logout').hidden=true;}throw Error(result.error||'请求失败');}return result;}
function date(value){return value?new Date(value).toLocaleString():'尚无访问';}
function cell(row,text){const td=document.createElement('td');td.textContent=text;row.append(td);return td;}
function button(parent,text,action){const b=document.createElement('button');b.textContent=text;b.className='secondary';b.addEventListener('click',async()=>{b.disabled=true;try{await action();}catch(e){message(e.message,true);}finally{b.disabled=false;}});parent.append(b);}
async function copy(text){await navigator.clipboard.writeText(text);message('链接已复制。');}
async function refresh(){const data=await api('/api/links');site=data.site;$('login').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('total').textContent=data.links.length;$('rows').replaceChildren();$('empty').hidden=!!data.links.length;for(const link of data.links){const row=document.createElement('tr');const name=cell(row,link.label);const detail=document.createElement('small');detail.textContent=link.path+(link.active?'':' · 已停用');name.append(detail);cell(row,String(link.visits)).className='count';cell(row,date(link.last_visit));const actions=cell(row,'');button(actions,'复制链接',()=>copy(site+link.path+'?ref='+link.code));button(actions,'查看记录',async()=>{const data=await api('/api/links/'+link.code+'/visits');$('detail-title').textContent=link.label;$('detail-list').replaceChildren();for(const v of data.visits){const p=document.createElement('p');p.textContent=date(v.visited_at)+' — '+v.path;$('detail-list').append(p);}if(!data.visits.length)$('detail-list').textContent='尚无访问记录。';$('details').showModal();});button(actions,link.active?'停用':'启用',async()=>{await api('/api/links/'+link.code,'PATCH',{active:!link.active});await refresh();message(link.active?'链接已停用，之后的访问不再记录。':'链接已启用。');});$('rows').append(row);}}
$('login').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/login','POST',{password:$('password').value});$('password').value='';await refresh();message('已登录。');}catch(e){message(e.message,true);}});
$('create').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const result=await api('/api/links','POST',{label:$('label').value,path:$('path').value});$('output').value=result.url;$('generated').hidden=false;$('label').value='';await refresh();message('专属链接已生成。');}catch(e){message(e.message,true);}finally{b.disabled=false;}});
$('copy-new').onclick=()=>copy($('output').value).catch(()=>message('复制失败，请手动复制链接。',true));$('refresh').onclick=()=>refresh().catch(e=>message(e.message,true));$('close').onclick=()=>$('details').close();$('logout').onclick=async()=>{try{await api('/api/logout','POST');location.reload();}catch(e){message(e.message,true);}};refresh().catch(()=>{});
</script></body></html>`;
